# Generated by Django 2.0.7 on 2018-10-30 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Autorizacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('justification_Aceit', models.TextField(blank=True, null=True, verbose_name='Justificativa')),
                ('status', models.IntegerField(choices=[(0, 'Negada'), (1, 'Andamento'), (2, 'Andamento'), (3, 'Aceita')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Motivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Motivo',
                'verbose_name_plural': 'Motivos',
            },
        ),
        migrations.CreateModel(
            name='Planejamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('components', models.CharField(max_length=100, verbose_name='Componente Curricular')),
                ('date_class', models.DateField(verbose_name='Data da Aula')),
                ('date_restitution', models.DateField(verbose_name='Data da Reposição')),
                ('descripition', models.TextField(verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Planejamento',
                'verbose_name_plural': 'Planejamentos',
            },
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('justification', models.TextField(verbose_name='Justificativa')),
                ('date_miss_start', models.DateField(verbose_name='Data da Falta Inicial')),
                ('date_miss_end', models.DateField(verbose_name='Data da Falta Final')),
                ('othes', models.CharField(blank=True, max_length=200, null=True, verbose_name='Outros')),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reposicao.Motivo')),
            ],
            options={
                'verbose_name': 'Solicitação',
                'verbose_name_plural': 'Solicitações',
            },
        ),
        migrations.CreateModel(
            name='Troca',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('mensagem', models.TextField(verbose_name='mensagem')),
                ('status', models.IntegerField(choices=[(0, 'Negada'), (1, 'Andamento'), (2, 'Aceita')], default=1)),
                ('solicitado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trocas', to=settings.AUTH_USER_MODEL, verbose_name='solicitado')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trocadeaula', to=settings.AUTH_USER_MODEL, verbose_name='solicitante')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('period', models.IntegerField(verbose_name='Período')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
            },
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reposicao.Turma'),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='planejamento',
            name='solicitation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reposicao.Solicitacao'),
        ),
        migrations.AddField(
            model_name='planejamento',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reposicao.Turma'),
        ),
        migrations.AddField(
            model_name='autorizacao',
            name='solicitation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reposicao.Solicitacao'),
        ),
    ]
