# Generated by Django 2.0.7 on 2018-11-19 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reposicao', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authorization',
            options={'verbose_name': 'Autorização', 'verbose_name_plural': 'Autorizações'},
        ),
    ]
