# Generated by Django 2.0.7 on 2018-10-30 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reposicao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planejamento',
            name='team',
        ),
    ]
